#!/usr/bin/env bash
PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Styles
thm_bg="#24273a"
thm_fg="#cad3f5"
thm_cyan="#91d7e3"
thm_black="#1e2030"
thm_gray="#363a4f"
thm_magenta="#c6a0f6"
thm_pink="#f5bde6"
thm_red="#ed8796"
thm_green="#a6da95"
thm_yellow="#eed49f"
thm_blue="#8aadf4"
thm_orange="#f5a97f"
thm_black4="#5b6078"

window_tabs_enabled="on"
date_time_fmt="%H:%M"
user_enabled="off"
host_enabled="off"

get_tmux_option() {
	local option value default
	option="$1"
	default="$2"
	value="$(tmux show-option -gqv "$option")"

	if [ -n "$value" ]; then
		echo "$value"
	else
		echo "$default"
	fi
}

set() {
	local option=$1
	local value=$2
	tmux_commands+=(set-option -gq "$option" "$value" ";")
}

setw() {
	local option=$1
	local value=$2
	tmux_commands+=(set-window-option -gq "$option" "$value" ";")
}

main() {
	# Aggregate all commands in one array
	local tmux_commands=()

	# status
	set status "on"
	set status-bg "${thm_bg}"
	set status-justify "left"
	set status-left-length "100"
	set status-right-length "100"

	# messages
	set message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
	set message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"

	# panes
	set pane-border-style "fg=${thm_gray}"
	set pane-active-border-style "fg=${thm_magenta}"

	# windows
	setw window-status-activity-style "fg=${thm_orange},bg=${thm_bg},none"
	setw window-status-separator ""
	setw window-status-style "fg=${thm_orange},bg=${thm_bg},none"

	# --------=== Statusline

	# NOTE: Checking for the value of @catppuccin_window_tabs_enabled
	local wt_enabled
	wt_enabled=${window_tabs_enabled:-"off"}
	readonly wt_enabled

	local right_separator
	right_separator=${right_sep:-""}
	readonly right_separator

	local left_separator
	left_separator=${left_sep:-""}
	readonly left_separator

	local user
	user=${user_enabled:-"off"}
	readonly user

	local host
	host=${host_enabled:-"off"}
	readonly host

	local date_time
	date_time=${date_time_fmt:-"off"}
	readonly date_time

	local tmux_session
	readonly tmux_session="#{?client_prefix,#[bg=$thm_red],#[bg=$thm_magenta]} #{?client_prefix,#[bg=$thm_red],#[bg=$thm_magenta]}#[fg=$thm_bg] #S #{?client_prefix,#[fg=$thm_red],#[fg=$thm_magenta]}#[bg=$thm_bg]$left_separator"

	# local show_window
	# readonly show_window="#[fg=$thm_pink,bg=$thm_bg,nobold,nounderscore,noitalics]$right_separator#[fg=$thm_bg,bg=$thm_pink,nobold,nounderscore,noitalics] #[fg=$thm_fg,bg=$thm_gray] #W #{?client_prefix,#[fg=$thm_red]"

	# local show_directory_in_window_status
	# #readonly show_directory_in_window_status="#[fg=$thm_bg,bg=$thm_blue] #I #[fg=$thm_fg,bg=$thm_gray] #{b:pane_current_path} "
	# readonly show_directory_in_window_status="#[fg=$thm_bg,bg=$thm_blue] #I #[fg=$thm_fg,bg=$thm_gray] #W "

	# local show_directory_in_window_status_current
	# # readonly show_directory_in_window_status_current="#[fg=$thm_bg,bg=$thm_orange] #I #[fg=$thm_fg,bg=$thm_bg] #{b:pane_current_path} "
	# readonly show_directory_in_window_status_current="#[fg=colour232,bg=$thm_orange] #I #[fg=colour255,bg=colour237] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) "

	local background_tab
	readonly background_tab="#[fg=$thm_blue,bg=$thm_gray]$right_separator#[fg=$thm_bg,bg=$thm_blue]#I #[fg=$thm_fg,bg=$thm_gray] #W #[fg=$thm_fg,bg=$thm_bg,nobold,nounderscore,noitalics]"

	local current_tab
	readonly current_tab="#[fg=$thm_orange,bg=$thm_gray]$right_separator#[fg=$thm_bg,bg=$thm_orange]#I #[fg=$thm_fg,bg=$thm_gray] #W #[fg=$thm_fg,bg=$thm_bg,nobold,nounderscore,noitalics]"


	local session_dir
	readonly session_dir="#[fg=$thm_green,bg=$thm_bg,nobold,nounderscore,noitalics]$right_separator#[fg=$thm_bg,bg=$thm_green,nobold,nounderscore,noitalics]󰴉 #[bg=$thm_gray,fg=$thm_green]▌#[fg=$thm_fg,bg=$thm_gray] #{b:pane_current_path} " #{?client_prefix,#[fg=$thm_red]

	local user
	readonly user="#[fg=$thm_blue,bg=$thm_gray]$right_separator#[fg=$thm_bg,bg=$thm_blue] #[fg=$thm_fg,bg=$thm_gray] #(whoami) "

	local host
	readonly host="#[fg=$thm_blue,bg=$thm_gray]$right_separator#[fg=$thm_bg,bg=$thm_blue]󰒋 #[fg=$thm_fg,bg=$thm_gray] #H "

	local time
	readonly time="#[fg=$thm_blue,bg=$thm_gray]$right_separator#[fg=$thm_bg,bg=$thm_blue]󰥔 #[bg=$thm_gray,fg=$thm_blue]▌#[fg=$thm_fg,bg=$thm_gray] $date_time"

	local right_column1=$session_dir
	local right_column2=""
	# local right_column2=$show_session
	# local right_column2=$show_date_time

	# local window_status_format=$show_window_in_window_status
	# local window_status_current_format=$show_window_in_window_status_current

	if [[ "${user}" == "on" ]]; then
		right_column2=$right_column2$user
	fi

	if [[ "${host}" == "on" ]]; then
		right_column2=$right_column2$host
	fi

	if [[ "${date_time}" != "off" ]]; then
		right_column2=$right_column2$time
	fi

	set status-left "$tmux_session#[bg=$thm_bg] "

	set status-right "${right_column1}${right_column2} "

	setw window-status-format "${background_tab}"
	setw window-status-current-format "${current_tab}"

	setw clock-mode-colour "${thm_blue}"
	setw mode-style "fg=default bg=${thm_black4} bold"

	tmux "${tmux_commands[@]}"
}

main "$@"
