#!/bin/sh

userresources="$XDG_CONFIG_HOME"/X11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start gtk and systemd user
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandrcmd=""

if xrandr | grep -q "DP-0 connected"; then
  xrandrcmd+="--output DP-0 --primary --mode 2560x1440 "
fi

if xrandr | grep -q "DP-2 connected"; then
    xrandrcmd+="--output DP-2 --mode 1920x1080 --left-of DP-0 --rotate right "
fi

if xrandr | grep -q "HDMI-0 connected"; then
  xrandrcmd+="--output HDMI-0 --mode 1920x1080 --right-of DP-0 "
fi

xrandr $xrandrcmd

xset s off -dpms
setxkbmap code-dvorak
nitrogen --restore &
picom --config $XDG_CONFIG_HOME/picom/picom.conf &
xsetroot -cursor_name left_ptr &
exec xmonad
