#!/usr/bin/env bash

handle() {
    case $1 in
        openwindow*)
            # focus albert when it opens
            if [[ $1 == *"albert"* ]]; then
                hyprctl dispatch focuswindow "albert"
            fi
            ;;
    esac
}

socat - UNIX-CONNECT:$(find /tmp/hypr -name ".socket2.sock") | while read -r line; do handle "$line"; done
