#!/usr/bin/env bash

if [[ -z $1 ]]; then
    screens="right main left"
    screen=`printf "%s\n" $screens | fzf`
else
    screen=$1
fi

case $screen in
    "main")
        screen=0
        ;;
    "left")
        screen=1
        ;;
    "right")
        screen=2
        ;;
    *)
        echo "invalid screen" && exit 1
        ;;
esac
xsetwacom set "Wacom Intuos BT S Pen stylus" MapToOutput "HEAD-$screen"

# config stylus
xsetwacom set "Wacom Intuos BT S Pen stylus" PressureCurve 0 100 40 80
xsetwacom set "Wacom Intuos BT S Pen stylus" Button 2 21
xsetwacom set "Wacom Intuos BT S Pen stylus" Button 3 22

# config pad
xsetwacom set "Wacom Intuos BT S Pad pad" Button 1 "key del"
xsetwacom set "Wacom Intuos BT S Pad pad" Button 2 "key +ctrl z -ctrl"
xsetwacom set "Wacom Intuos BT S Pad pad" Button 3 "key +ctrl c -ctrl"
xsetwacom set "Wacom Intuos BT S Pad pad" Button 8 "key +ctrl v -ctrl"
