#!/usr/bin/env bash

hid() {
	tmux list-windows -F '#{window_name}' | grep -q ' '
}

no_bot() {
	tmux list-panes -F '#{pane_at_left} #{pane_at_top} #{pane_at_bottom}' | grep -q '1 1 1'
}

if hid; then
	tmux select-pane -t 0
	tmux join-pane -v -l 30% -s ' '
elif no_bot; then
	tmux select-pane -t 0
	tmux split-window -c "#{pane_current_path}" -v -p 30
else
	tmux select-pane -t 1
	tmux break-pane -d -n ' ' -t $(($(tmux list-windows -F '#{window_index}' | tail -n1) + 1))
	[[ $HOSTNAME = "coeus" ]] && sleep 0.01 || sleep 0.3
	tmux next-window
	tmux previous-window
fi
