#!/bin/bash

## Get data
STATUS="$(playerctl -p spotify status)"
COVER="/tmp/.music_cover.jpg"
PREVCOVER="/tmp/.prev_music_cover"

## Get status
get_status() {
	if [[ $STATUS == "Playing" ]]; then
		echo "󰏥"
	else
		echo "󰐌"
	fi
}

## Get song
get_song() {
	song=$(playerctl -p spotify metadata --format "{{ title }}")
	if [[ -z "$song" ]]; then
		echo "Nothing playing"
	else
		echo "$song"
	fi
}

## Get artist
get_artist() {
	artist=$(playerctl -p spotify metadata --format "{{ artist }}")
	song=$()
	if [[ -z "$artist" ]]; then
		echo ""
	else
		echo "$artist"
	fi
}

get_time() {
	time=$(playerctl -p spotify metadata --format "{{ duration(mpris:length) }}")

	position=$(playerctl -p spotify position)
	length=$(playerctl -p spotify metadata mpris:length)
	length=$(echo "scale=2; $length / 1000000" | bc)
	time=$(printf "%.0f" $(echo "scale=2; $position / $length * 100" | bc))

	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo $time
	fi
}
get_ctime() {
	ctime=$(playerctl -p spotify metadata --format "{{ duration(position) }}")
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi
}
get_ttime() {
	ttime=$(playerctl -p spotify metadata --format "{{ duration(mpris:length) }}")
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi
}

## Get cover
get_cover() {
	arturl=$(playerctl -p spotify metadata --format "{{mpris:artUrl}}")
	[[ ! -f $PREVCOVER ]] && touch $PREVCOVER
	prevarturl=$(cat $PREVCOVER)

	if [[ -z "$arturl" ]]; then
		echo "images/music.png"
	elif [[ "$arturl" == "$prevarturl" ]]; then
		echo "$COVER"
	else
		curl -s "$arturl" >"$COVER"
		echo "$COVER"
	fi

	echo $arturl >$PREVCOVER
}

if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	playerctl -p spotify play-pause
elif [[ "$1" == "--next" ]]; then
	{
		playerctl -p spotify next
		get_cover
	}
elif [[ "$1" == "--prev" ]]; then
	{
		playerctl -p spotify previous
		get_cover
	}
fi
