#!/bin/bash

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)
cmd="firefox --new-tab"

close_dash() {
	${EWW} --config "$CFG" close \
		background profile system clock cal music github \
		hackernews twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--mail" ]]; then
	close_dash && focus-mail

elif [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com"

elif [[ "$1" == "--hn" ]]; then
	close_dash && ${cmd} "https://news.ycombinator.com"

elif [[ "$1" == "--tw" ]]; then
	close_dash && ${cmd} "https://twitter.com"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${cmd} "https://youtube.com"

fi
