#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)

close_dash() {
	${EWW} --config "$CFG" close \
		background profile system clock cal music github \
		hackernews twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--firefox" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--term" ]]; then
	close_dash && kitty &

elif [[ "$1" == "--calendar" ]]; then
	close_dash && firefox https://calendar.cron.com &

elif [[ "$1" == "--tr" ]]; then
	close_dash && kitty &

elif [[ "$1" == "--fm" ]]; then
	close_dash && nemo ~ &

elif [[ "$1" == "--ge" ]]; then
	close_dash && geany &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--gp" ]]; then
	close_dash && gimp &

elif [[ "$1" == "--vb" ]]; then
	close_dash && virtualbox &

fi
