#!/usr/bin/env bash

send_notification() {
    local brightness=$1
    local temp=$2

    notify-send "Brightness" "${temp}K" -h int:value:"$brightness" --icon ~/.config/dunst/images/brightness.png -r 5678
}

get_brightness() {
    local gamma
    if command -v brillo &>/dev/null; then
        gamma=$(brillo -G)
    else
        gamma=$(hyprctl hyprsunset gamma)
    fi
    echo ${gamma%.*}
}

get_temperature() {
    local temp=$(hyprctl hyprsunset temperature)
    echo ${temp%.*}
}

case $1 in
up)
    if command -v brillo &>/dev/null; then
        sudo brillo -A 5
    else
        hyprctl hyprsunset gamma +5
    fi
    send_notification $(get_brightness) $(get_temperature)
    ;;
down)
    if command -v brillo &>/dev/null; then
        sudo brillo -U 5
    else
        hyprctl hyprsunset gamma -5
    fi
    send_notification $(get_brightness) $(get_temperature)
    ;;
temp-up)
    hyprctl hyprsunset temperature +250
    send_notification $(get_brightness) $(get_temperature)
    ;;
temp-down)
    hyprctl hyprsunset temperature -250
    send_notification $(get_brightness) $(get_temperature)
    ;;
set)
    if command -v brillo &>/dev/null; then
        sudo brillo -S $2
    else
        hyprctl hyprsunset gamma $2
    fi
    send_notification $(get_brightness) $(get_temperature)
    ;;
next)
    gamma=$(get_brightness)
    levels=(1 5 20 50 75 90 100)
    current_int=${gamma%.*}
    echo "current: $current_int"
    next_level=1
    for level in "${levels[@]}"; do
        if ((current_int < level)); then
            next_level=$level
            break
        fi
    done
    brightness set $next_level
    ;;
*)
    hyprctl hyprsunset gamma
    hyprctl hyprsunset temperature
    ;;
esac
