#!/usr/bin/env bash
source parseargs

[[ -d ~/cloud ]] || mkdir ~/cloud
[[ -d ~/cloud/box ]] || mkdir ~/cloud/box
# [[ -d ~/cloud/gdrive ]] || mkdir ~/cloud/gdrive

case $1 in
mount)
	if [[ $2 == "all" ]]; then
		# currently dir is the full path, need to modify to just get the end
		for dir in ~/cloud/*; do
			name=$(basename $dir)
			echo "Mounting $name"
			rclone mount $name: $dir --daemon --vfs-cache-mode writes
			cloud link $name
		done
	else
		rclone mount $2: ~/cloud/$2 --daemon --vfs-cache-mode writes
		cloud link $2
	fi

	;;
umount)
	if [[ $2 == "all" ]]; then
		for dir in ~/cloud/*; do
			umount $dir
			cloud unlink $(basename $dir)
		done
	else
		umount ~/cloud/$2 || lsof "$HOME/cloud/$2"
		cloud unlink $2
	fi
	;;
setup)
    rclone config
    ;;
link)
	ln -s ~/cloud/$2 ~
	;;
unlink)
	if [[ -e ~/$2 ]]; then
		rm ~/$2
	fi
	;;
mounted)
	any=0
	for dir in ~/cloud/*; do
		name=$(basename $dir)
		mountpoint -q $dir && echo $name && any=1
	done

	if [[ $any == 0 ]]; then
		echo "no"
	fi
	;;
*)
	echo "Invalid command"
	exit 1
	;;
esac
