#!/usr/bin/env zsh

# setup dirs
dirs=(
    .config $XDG_CONFIG_HOME
    scripts $HOST_DOTFILES/scripts
    dotfiles $DOTFILES
    nvim $XDG_CONFIG_HOME/nvim
    chat.nvim ~/projects/chat.nvim
    projects ~/projects
    kbd ~/kbd
)
for location in "$XDG_CONFIG_HOME" "$HOME/projects"; do
    for dir in "$location"/*; do
        if [ -d "$dir" ]; then
            dir_name=$(basename "$dir")
            if [[ "$dir_name" == *" "* ]]; then
                continue
            fi
            if [[ ! " ${dirs[@]} " =~ " ${dir_name} " ]]; then
                dirs+=("$dir_name" "$dir")
            fi
        fi
    done
done

# main script start

tmux=false
file=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        tmux) tmux=true ;;
        file) file=true ;;
        *) break ;;
    esac
    shift
done

fzfcmd="fzf --with-nth 1"
if [[ $tmux == false ]]; then
    fzfcmd="$fzfcmd --height=20% --border --layout=reverse"
fi

# select top level dir
sel=`printf "%s %s\n" $dirs | eval "$fzfcmd"`
name=`echo "$sel" | awk '{print $1}'`
dir=`echo "$sel" | awk '{print $2}'`

# select file
if [[ $file == true ]] ; then
    [[ -z $dir ]] && exit

    files=`find -L "$dir" -type f -printf "%f %p\n"`
    sel=`printf "%s\n" $files | eval "$fzfcmd"`
    file=`echo "$sel" | awk '{print $2}'`

    if [[ $tmux == true ]] && [[ ! -z $file ]]; then
        tmux new-window -n "cfg-$name" -c "$dir" -d
        echo $?
        tmux send-keys -t "cfg-$name" "nvim $file" ENTER
        echo $?
        tmux select-window -t "cfg-$name"
        echo $?
    else
        echo "$file"
    fi

else
    if [[ $tmux == true ]] && [[ ! -z $dir ]]; then
        tmux new-window -n "cfg-$name" -c "$dir" -d
        tmux send-keys -t "cfg-$name" "clear; la" ENTER
        tmux select-window -t "cfg-$name"
    else
        echo "$dir"
    fi
fi


