#!/usr/bin/env python

import os
import re
from datetime import date, datetime

expected = [
    ".zshrc",
    ".ssh",
    "kbd",
    "projects",
    ".cache",
    ".local",
    ".thunderbird",
    ".mozilla",
    ".dotfiles",
    "scripts",
    "Downloads",
    ".config",
    ".ghc",
    ".pki",
    ".minecraft",
    "cloud",
]

home_path = os.path.expanduser("~")
home_files = os.listdir(home_path)

unexpected = [f for f in home_files if f not in expected]

if unexpected:
    print("Unexpected files in home dir:")
    for f in unexpected:
        if f == "Desktop":
            os.rmdir(os.path.join(home_path, f))
        else:
            print(" ", f)
    print()
