#!/usr/bin/env bash

teams=""
slack=""
discord="ﭮ"
zoom=""

options="$slack\n$zoom\n$teams\n$discord"

sel=$(echo -e "$options" | rofi -no-fixed-num-lines -theme $HOME/.config/rofi/commmenu.rasi -dmenu)

case $sel in
$slack)
	slack
	;;
$zoom)
	xdotool set_desktop 6
	zoom
	;;
$teams)
	teams
	;;
$discord)
	discord
	;;
esac
