#!/usr/bin/env bash

# A rebuild script that commits on a successful build
set -e

# cd to your config dir
pushd ~/.config/nixos &>/dev/null

# Edit your config
if [[ -z $1 ]]; then
    FILE=$(find . -type f,l | sed 's|^\./||' | fzf)
else
    FILE=$1
fi
[[ -z $FILE ]] && exit 1
[[ $FILE == "config" ]] && FILE="configuration.nix"
[[ $FILE != *.nix ]] && FILE="$FILE.nix"
nvim $FILE

# Autoformat your nix files
# alejandra . &>/dev/null

# Shows your changes
pushd $HOST_DOTFILES/.config/nixos
git diff -U0 *.nix
popd

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
sudo cp *.nix /etc/nixos/
# sudo nixos-rebuild switch --flake /etc/nixos#default --impure &>nixos-switch.log || (cat nixos-switch.log | grep --color error && false)
{ sudo nixos-rebuild switch --flake /etc/nixos#default --impure 2>&1 | tee nixos-switch.log; } || cat nixos-switch.log | grep --color error >&2


# Get current generation metadata
# current=$(nixos-rebuild list-generations | grep current)

# Commit all changes within the generation metadata
# git commit -am "$current"

# Back to where you were
popd &>/dev/null

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
