#!/usr/bin/env bash

# A rebuild script that commits on a successful build
set -e

# cd to your config dir
pushd $HOST_DOTFILES/.config/nixos &>/dev/null

# Edit your config
FILE=configuration.nix
case $1 in
    packages)
        FILE=packages.nix
        ;;
    host)
        FILE=host.nix
        ;;
esac
nvim $FILE

# Autoformat your nix files
# alejandra . &>/dev/null

# Shows your changes
git diff -U0 *.nix

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
sudo cp *.nix /etc/nixos/
sudo nixos-rebuild switch &>nixos-switch.log || (cat nixos-switch.log | grep --color error && false)

# Get current generation metadata
# current=$(nixos-rebuild list-generations | grep current)

# Commit all changes within the generation metadata
# git commit -am "$current"

# Back to where you were
popd &>/dev/null

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
