#!/usr/bin/env bash


# update only specific input (channel): sudo nix flake lock --update-input nixpkgs-unstable
if [[ $1 == "update" ]]; then
    cd /etc/nixos
    sudo nix-collect-garbage --delete-older-than 7d
    sudo nix flake update
    sudo nixos-rebuild switch --flake /etc/nixos#default --impure --upgrade
    exit
fi

set -e
pushd ~/.config/nixos &>/dev/null

# Edit your config
if [[ -z $1 ]]; then
    FILE=$(find . -type f,l | sed 's|^\./||' | fzf)
else
    FILE=$1
fi
[[ -z $FILE ]] && exit 1
[[ $FILE == "config" ]] && FILE="configuration.nix"
[[ $FILE != *.nix ]] && FILE="$FILE.nix"
nvim $FILE

# Autoformat your nix files
# alejandra . &>/dev/null

# Shows your changes
pushd $HOST_DOTFILES/.config/nixos
git diff -U0 *.nix
popd

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
sudo cp *.nix /etc/nixos/

{ sudo nixos-rebuild switch --flake /etc/nixos#default --impure 2>&1 | tee nixos-switch.log; } || cat nixos-switch.log | grep --color error >&2

popd &>/dev/null

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
