#!/usr/bin/env bash
source parseargs

# Incase something breaks, use if statement and -s flag
# if [[ $bools =~ .*s.* ]]; then
#     IFS=""
# fi

IFS=""
for f in ${args[@]}; do
	xdg-open "$f" &>/dev/null &
	disown
done
