#!/usr/bin/env bash

polybar-msg cmd toggle

# CACHE_FILE="$HOME/.cache/polybar-toggle-state"
CACHE_FILE="/tmp/polybar-toggle-state"
[[ ! -f "$CACHE_FILE" ]] && echo "1" >"$CACHE_FILE"

# flip state
STATE=$(cat "$CACHE_FILE")
[[ $STATE == "0" ]] && STATE="1" || STATE="0"
echo "$STATE" >"$CACHE_FILE"
