#!/usr/bin/env bash

if [[ -n $1 ]]; then
	name="$1"
elif [[ -f ".venv" ]]; then
	name=$(cat .venv)
	rm .venv
else
	echo "no venv provided and no .venv in dir"
	exit 1
fi

rm -rf "$VIRTUALENV_HOME/$name"

if [[ -d "$HOME/.local/share/jupyter/kernels/$name" ]]; then
	rm -rf "$HOME/.local/share/jupyter/kernels/$name"
fi
