#!/usr/bin/env bash

i=$(tmux display-message -p '#I')

case $1 in
l | left | p | prev)
	dest=$((i - 1))
	;;
r | right | n | next)
	dest=$((i + 1))
	;;
*)
	dest=$i
	;;
esac

tmux swap-window -t $dest -d
exit 0
