#!/usr/bin/env bash

TODO_FILE="$HOME/.cache/todo"
if [[ ! -f "$TODO_FILE" ]]; then touch "$TODO_FILE"; fi

if [[ $# -eq 0 ]]; then
	echo "--- TODO ---"
	cat -n $TODO_FILE
	exit 0
else
	case $1 in
	e | -e)
		nvim $TODO_FILE
		;;
	c | -c)
		>$TODO_FILE
		echo "Cleared all todos"
		;;
	a | -a)
		shift
		todo_item="$@"
		IFS=$'\n'
		read -ra todo_lines <<<"$todo_item"
		for line in "${todo_lines[@]}"; do
			if [[ -z "$line" ]]; then
				continue
			fi
			echo "$line" >>"$TODO_FILE"
		done
		todo
		;;
	d | -d)
		shift
		if [[ $1 =~ ^[0-9]+-[0-9]+$ ]]; then
			start=$(echo $1 | cut -d'-' -f1)
			end=$(echo $1 | cut -d'-' -f2)
			count=0
			n=$(($end - $start))
			for ((i = $start; i <= $end; i++)); do
				sed -i "$start"d $TODO_FILE
			done
		else
			sed -i "$1d" $TODO_FILE
		fi
		todo
		;;
	*)
        # check - not in the first arg
        if [[ $1 =~ ^- ]]; then
            echo "Invalid option"
            exit 1
        fi
		todo a "$@"
		;;
	esac
fi
