#!/usr/bin/env bash

PERCENT=20

term_hidden() {
	tmux list-windows -F '#{window_name}' | grep -q ' '
}

get_hid_term() {
	tmux list-windows -F '#{window_name}::#{window_id}' | grep ' ' | awk -F '::' '{print $2}' | head -n1
}

get_panes_below() {
	if [[ $(tmux display-message -p '#{pane_at_top}') -ne 1 ]]; then tmux select-pane -U; fi
	tmux list-panes -F '#{pane_id} #{pane_top} #{pane_bottom}' | awk -v top=$(tmux display -p '#{pane_top}') -v bottom=$(tmux display -p '#{pane_bottom}') '$2 > bottom'
}

get_panes_beside() {
	tmux select-pane -L
	tmux list-panes -F '#{pane_id} #{pane_left} #{pane_right}' | awk -v left=$(tmux display -p '#{pane_left}') -v right=$(tmux display -p '#{pane_right}') '$2 > right'
}

d=${1:-h}

case $d in
h)
	if [[ $(get_panes_below | wc -l) -eq 0 ]]; then
		if term_hidden; then
			tmux join-pane -v -l "$PERCENT"% -s $(get_hid_term)
		else
			tmux split-window -c "#{pane_current_path}" -v -l "$PERCENT"%
		fi
	else
		tmux select-pane -D
		tmux break-pane -d -n ' ' -t $(($(tmux list-windows -F '#{window_index}' | tail -n1) + 1))
	fi
	;;
v)
	if [[ $(get_panes_beside | wc -l) -eq 0 ]]; then
		if term_hidden; then
			tmux join-pane -h -l "$PERCENT"% -s $(get_hid_term)
		else
			tmux split-window -c "#{pane_current_path}" -v -l $PERCENT
		fi
	else
		tmux select-pane -R
		tmux break-pane -d -n ' ' -t $(($(tmux list-windows -F '#{window_index}' | tail -n1) + 1))
	fi
	;;
*)
	echo "invalid dir: h or v"
	;;
esac
