#!/usr/bin/env bash

PERCENT=20

TT_SESSION="tt"
session=$(tmux display-message -p '#S')
tt_pane="tt-$session"
window=$(tmux display-message -p '#S:#I')
# echo "tt_pane: $tt_pane"
# echo "window: $window"

if ! tmux has-session -t "$TT_SESSION" 2>/dev/null; then
	# echo "starting tt session"
	tmux new-session -d -s "$TT_SESSION"
    tmux switch-client -t "$session"
fi

if ! tmux list-panes -a -F '#{pane_title}' | grep -q "$tt_pane"; then
	# echo "creating tt pane"
	tmux split-window -c "#{pane_current_path}" -v -l "$PERCENT"% \; select-pane -T $tt_pane
else
	# echo "tt pane exists"
	tt_pane_id=$(tmux list-panes -a -F '#S:#I.#P|#{pane_title}' | grep "$tt_pane" | cut -d"|" -f1)
    # echo "tt_pane_id: $tt_pane_id"
    if tmux list-panes -F '#S:#I #{pane_title}' | grep -q "$window $tt_pane"; then
		# echo "pane in current window, sending to tt session"
		tmux join-pane -s "$tt_pane_id" -t "$TT_SESSION"
	else
		# echo "pane not in current window, joining"
		tmux join-pane -s "$tt_pane_id" -l "$PERCENT"%
	fi
fi

