#!/usr/bin/env bash

if [[ $1 != "0" && $1 != "1" ]]; then
	echo "Usage: barmon [0|1]"
	return
fi
new=$1
old=$((1 - $new))
find -L ~/.config/eww/bar -type f -exec sed -i "s/:monitor $old/:monitor $new/g" {} +
