#!/bin/bash

hostname=`hostname`
monitor=`sudo ddcutil detect | grep DEL -B 2 | head -n 1 | awk '{print $3}' | tail -c 3`

function notification() {
    icon="$HOME/.local/share/icons/Qogir-dark/16/panel/gpm-brightness-lcd.svg"

    case $hostname in
        coeus)
            brightness=`sudo ddcutil getvcp 10 | awk '{ print $9 }' | sed 's/,//g'`
            polybar-msg -p "$(pgrep -f "polybar top")" hook brightness 1 &>/dev/null
            ;;

        prometheus)
            brightness=`xbacklight -get | cut -d '.' -f 1`
            ;;
    esac

    if [[ $1 == 1 ]]
    then
        brightness=$(expr $brightness + 10)
    elif [[ $1 == -1 ]]
    then
        brightness=$(expr $brightness - 10)
    fi

    bar=$(seq -s "─" 0 $((brightness / 3)) | sed 's/[0-9]//g')

    # dunstify -i "$icon" -r 5555 -u normal " $bar"
	dunstify "Brightness" -r 2593 -u normal -h int:value:"$brightness" --icon ~/.config/dunst/images/brightness.png
}

case $1 in
    up)
        notification 1
        case $hostname in
            coeus)
                sudo ddcutil --bus $monitor setvcp 10 + 10
                ;;
            prometheus)
                xbacklight -inc 2.5
                ;;
        esac
        ;;
    down)
        notification -1
        case $hostname in
            coeus)
                sudo ddcutil --bus $monitor setvcp 10 - 10
                ;;
            prometheus)
                xbacklight -dec 2
                ;;
        esac
        ;;
    set)
        case $hostname in
            coeus)
                sudo ddcutil --bus $monitor setvcp 10 $2
                ;;
            prometheus)
                xbacklight -set $2
                ;;
        esac
        notification
        ;;
    get)
        case $hostname in
            coeus)
                sudo ddcutil getvcp 10 | awk '{ print $9 }' | sed 's/,//g'
                ;;

            prometheus)
                xbacklight -get | cut -d '.' -f 1
                ;;
        esac
        ;;
esac
