#!/bin/bash

DEVFILE=$HOME/.config/bt/devices

# Power on bluetooth controller
[[ `bluetoothctl show | rg "Powered" | awk '{print $2}'` == "yes" ]] || bluetoothctl power on

# Load associative array with device name -> mac address
IFS="\n"

readarray -t a < "$DEVFILE"

declare -A devices

for e in ${a[@]}; do
    k=`echo $e | awk '{print $1}'`
    v=`echo $e | awk '{print $2}'`
    devices+=( [$k]=$v )
done

has_dev() {
    [[ -v "devices[$1]" ]]
}

get_dev() {
    if [[ -n $1 ]]; then
        dev=$1
    else
        dev=`printf "%s\n" ${!devices[@]} | fzf --header="device menu" --info="hidden"`
    fi
    has_dev $dev || exit
    echo $dev # pseudo-return
}


case $1 in
    connect | con | c)
            dev=`get_dev $2`
            [[ -z $dev ]] && echo "Invalid device" && exit 1
            mac=${devices[$dev]}
            bluetoothctl connect $mac && notify-send "$dev connected" -i ~/.config/dunst/images/bluetooth.png || notify-send "could not connect $dev" -i ~/.config/dunst/images/bluetooth.png 
            [[ $dev = "wacom" ]] && config-wacom m
            [[ $dev = "airpods" ]] && pacmd list-cards | grep 'Bean Pods' -m 1 -B 5 | head -1 | xargs | awk '{print $2}' | xargs -I % pacmd set-card-profile % a2dp_sink
        ;;
    disconnect | discon | d)
            dev=`get_dev $2`
            [[ -z $dev ]] && echo "Invalid device" && exit 1
            mac=${devices[$dev]}
            bluetoothctl disconnect $mac && notify-send "$dev disconnected" -i ~/.config/dunst/images/bluetooth.png || notify-send "could not disconnect $dev" -i ~/.config/dunst/images/bluetooth.png 
        ;;
    toggle | tog | t)
        dev=`get_dev $2`
        [[ -z $dev ]] && echo "Invalid device" && exit 1
        mac=${devices[$dev]}
        connected=`bluetoothctl info | grep "$mac" -A 8 | grep "Connected" | awk '{ print $2 }'`
        if [[ $connected == 'yes' ]]; then
            bt disconnect $dev
        else
            bt connect $dev
        fi
        ;;
    add | a)
        [[ -z $2 || -z $3 ]] && echo "Usage: bt add [name] [mac]" && exit 1
        echo "$2 $3" >> "$DEVFILE" && echo "Sucessfully added $2 ($3) to the list of devices"
        ;;
    remove)
        [[ -z $2 ]] && echo "Usage: bt remove [name]" && exit 1
        ! has_dev $2 && echo "Invalid device \"$2\"" && exit 1
        sed -i "/^$2 /d" "$DEVFILE"
        ;;
    menu | m)
        icons="\n\n蓼"
        # printf "%s\n" ${!devices[@]}
        sel=`echo -e "$icons" | rofi -no-fixed-num-lines -theme $HOME/.config/bt/btmenu.rasi -dmenu`
        case $sel in
            )
                dev="airpods"
                ;;
            )
                dev="wacom"
                ;;
            蓼)
                dev="heater"
                ;;
        esac
        bt toggle $dev && [[ $dev = "wacom" ]] && notify-send "Run config-wacom"
        ;;
    restart | r)
        sudo killall bluetoothd
        sudo systemctl restart bluetooth
        ;;
    recon | rc)
        mac=""
        if [[ -n $2 ]]; then
            dev=`get_dev $2`
            [[ -z $dev ]] && echo "Invalid device" && exit 1
            mac=${devices[$dev]}
        fi
        bt-reconnect $mac
        ;;
    *)
        bluetoothctl $@
        ;;
esac
