#!/usr/bin/expect -f

if {$argc == 0} {
    set mac "E4:90:FD:90:2B:52"
} else {
    set mac [lindex $argv 0]
}

send_user "\nReconnecting $mac\n"

set timeout -1

spawn bluetoothctl
expect -re "#"

send "power on\n"
expect -re "succeeded"

send_user "\nRemoving device...\n"
send "remove $mac\n"
expect -re "removed|not available"
expect -re "#"

send_user "\nScanning for device...\n"
send "scan on\n"
expect -re "Device $mac"

send_user "\nDevice found\n"
send "scan off\n"
expect -re "Discovery stopped"

send_user "\nTrusting device...\n"
send "trust $mac\n"
expect -re "trust succeeded"

send_user "\nPairing...\n"
send "pair $mac\n"
expect -re "Pairing successful"

send_user "\nConnecting...\n"
send "connect $mac\n"
expect -re "Connection successful"

send "quit\n"
expect eof
