#!/usr/bin/env bash

bat=$(acpi | awk '{printf $4}' | tr -d "," | tr -d "%")
charging=$(acpi | awk '{printf $3}' | tr -d ",")

if [[ $charging == "Charging" ]]; then
	exit 0
fi

if (($bat <= 5)); then
	notify-send "critical battery" "$bat%" -u "critical" -i ~/.config/dunst/images/warning.png
elif (($bat <= 10)); then
	notify-send "very low battery" "$bat%" -u "critical" -i ~/.config/dunst/images/warning.png
elif (($bat <= 25)); then
	notify-send "low battery" "$bat%" -u "critical" -i ~/.config/dunst/images/warning.png
# else
# 	notify-send "battery" "$bat%" -u "critical" -i ~/.config/dunst/images/warning.png
fi
