#!/usr/bin/env bash

bat=$(acpi | awk '{printf $4}' | tr -d "," | tr -d "%")
charging=$(acpi | awk '{printf $3}' | tr -d ",")

if [[ $charging == "Discharging" ]]; then
	if (($bat <= 15)); then
		notify-send "low battery" "$bat%" -u "critical"
	fi
else
	(($bat >= 95)) && notify-send "battery charged" "$bat%"
	exit
fi
