#!/usr/bin/env bash
source parseargs

mkdir -p ~/cloud/box ~/cloud/gdrive ~/cloud/storj

case $1 in
mount)
	if [[ $2 == "all" ]]; then
		# currently dir is the full path, need to modify to just get the end
		for dir in ~/cloud/*; do
			name=$(basename $dir)
			echo "Mounting $name"
			rclone mount $name: $dir --daemon --vfs-cache-mode writes
		done
		exit
	fi

	rclone mount $2: ~/cloud/$2 --daemon --vfs-cache-mode writes
	;;
umount)
	if [[ $2 == "all" ]]; then
		for dir in ~/cloud/*; do
			umount $dir
		done
		exit
	fi

	umount ~/cloud/$2
	;;
*)
	echo "Invalid command"
	exit 1
	;;
esac
