#!/usr/bin/env bash
source parseargs

mkdir -p ~/cloud/box ~/cloud/gdrive ~/cloud/storj

case $1 in
mount)
	if [[ $2 == "all" ]]; then
		for dir in ~/cloud/*; do
			rclone mount $dir: ~/cloud/$dir --daemon --vfs-cache-mode writes
		done
		exit
	fi

	rclone mount $2: ~/cloud/$2 --daemon --vfs-cache-mode writes
	;;
umount)
	if [[ $2 == "all" ]]; then
		for dir in ~/cloud/*; do
			umount $dir
		done
		exit
	fi

	umount ~/cloud/$2
	;;
*)
	echo "Invalid command"
	exit 1
	;;
esac
