#!/usr/bin/env bash

if [[ $# > 0 ]]; then
    message="$@ (y/n) "
else
    message="Continue? (y/n) "
fi

printf "$message"
old_stty_cfg=$(stty -g)
stty raw -echo
answer=$(while ! head -c 1 | grep -i '[ny]'; do true; done)
stty $old_stty_cfg
if [ "$answer" != "${answer#[Yy]}" ]; then
	echo Yes
    exit 0
else
	echo No
    exit 1
fi
