#!/usr/bin/env bash

singleline() {
	symbols="▰ ━ ═ ▃ ▀▄ 󱨊󱨉 △▽"
	symbol=$(echo $symbols | tr " " "\n" | shuf -n 1)
	yes "$symbol" | head -n $(($(tput cols) / ${#symbol})) | tr "\n" "," | sed "s/,//g" | lolcat -F 0.04
	[[ $(($(tput cols) % ${#symbol})) != 0 ]] && echo " "
}

multiline() {
	seed=$(date +%N)
	yes "╮╭╮╭" | head -n $(($(tput cols) / 4)) | tr "\n" "," | sed "s/,//g" | lolcat -F 0.04 -S $seed
	# yes "◞◝" | head -n $(($(tput cols) / 1)) | tr "\n" "," | sed "s/,//g" | lolcat -F 0.04 -S $seed
	[[ $(($(tput cols) % 4)) != 0 ]] && echo " "
	# yes "◡" | head -n $(($(tput cols) / 1)) | tr "\n" "," | sed "s/,//g" | lolcat -F 0.04 -S $seed
	yes "╰╯╰╯" | head -n $(($(tput cols) / 4)) | tr "\n" "," | sed "s/,//g" | lolcat -F 0.04 -S $seed
	[[ $(($(tput cols) % 4)) != 0 ]] && echo " "
}

rand=$(echo -e "0\n1" | shuf -n 1)
mode=$((rand % 2))
if [[ $mode == 0 ]]; then
	singleline
else
	multiline
fi
exit 0
