#!/bin/bash

if [[ "$1" == "reset" ]]; then
	pid=$(ps -ef | rg "eyes" | rg -v "rg|reset" | awk '{ print $2 }')
	kill $pid
	runbg eyes
	exit
elif [[ "$1" == "toggle" ]]; then
    pid=$(ps -ef | rg "eyes" | rg -v "rg|toggle" | awk '{ print $2 }')
    if [[ -n "$pid" ]]; then
        kill $pid
    else
        runbg eyes
    fi
    exit
fi

INTERVAL=30

sleep "$INTERVAL"m
count=$(($1 + $INTERVAL)) # count how long its been since taking a break

ACTION=$(dunstify --action="default,run again" --action="stop,stop" "Take care of your eyes! 👀" "$count min without a break" -i ~/.config/dunst/images/eyes.png -u critical)

case $ACTION in
default) # left click
	brightness set 0
	while [[ $(brightness get) == 0 ]]; do
		sleep 1
	done
	notify-send "Welcome back!" -t 1000 -i ~/.config/dunst/images/eyes.png
	eyes &
	;;
stop) # middle click -> stop
	exit
	;;
1 | 2) # 1=expired, 2=dismissed (right click)
	eyes $count &
	;;
esac
