#!/usr/bin/env bash

launch=firefox
ws="special:browser"

if [[ $1 == "ask" ]]; then
	launch='firefox --new-window "https://ai.com"'
	ws="special:ask"
fi

if ! hyprctl clients | rg "class: firefox-aurora|class: firefoxdeveloperedition" -B3 | rg "($ws)" -q; then
	eval "$launch"
	sleep 0.5
	hyprctl dispatch movetoworkspace $ws
fi
