#!/usr/bin/env bash

# Set the source audio player here.
# Players supporting the MPRIS spec are supported.
# Examples: spotify, vlc, chrome, mpv and others.
# Use `playerctld` to always detect the latest player.
# See more here: https://github.com/altdesktop/playerctl/#selecting-players-to-control
PLAYER="spotify"

# Format of the information displayed
# Eg. {{ artist }} - {{ album }} - {{ title }}
# See more attributes here: https://github.com/altdesktop/playerctl/#printing-properties-and-metadata

if [[ -n `playerctl --player=spotify metadata --format "{{artist}}" 2>/dev/null` ]]; then
    ICON=""
    FORMAT="{{ title }} - {{ artist }}"
else
    ICON=""
    FORMAT="{{ title }} - {{ album }}"
fi

if [[ $1 = "icon" ]]; then
    echo $ICON
    exit
elif [[ ! $1 = "noicon" ]]; then
    FORMAT="$ICON $FORMAT"
fi

PLAYERCTL_STATUS=$(playerctl --player=$PLAYER status 2>/dev/null)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    STATUS=$PLAYERCTL_STATUS
else
    STATUS="None"
fi

case $STATUS in
    Playing)
        playerctl --player=$PLAYER metadata --format "$FORMAT"
        polybar-msg -p "$(pgrep -f "polybar music")" hook play-pause 1 &>/dev/null
        ;;
    Paused)
        playerctl --player=$PLAYER metadata --format "$FORMAT"
        polybar-msg -p "$(pgrep -f "polybar music")" hook play-pause 2 &>/dev/null
        ;;
    *)
        echo ""
        ;;
esac

