#!/usr/bin/env bash
git clone https://github.com/jeffreytse/zsh-vi-mode ${ZSH_CUSTOM:-~/.config/zsh/oh-my-zsh/custom}/plugins/zsh-vi-mode
git clone https://github.com/zdharma/fast-syntax-highlighting ${ZSH_CUSTOM:-~/.config/zsh/oh-my-zsh/custom}/plugins/fast-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.config/zsh/oh-my-zsh/custom}/plugins/zsh-autosuggestions
