#!/bin/bash

if [[ $# = 0 ]]; then
    killall -q polybar
    sleep 3 # wait for polybar to shutdown, should be more than enough time

    polybar workspaces -c $HOME/.config/polybar/config.ini &
    polybar sys -c $HOME/.config/polybar/config.ini &
    polybar datetime -c $HOME/.config/polybar/config.ini &
else
    polybar $1 -c $HOME/.config/polybar/config.ini &
fi

