#!/bin/bash

if [[ $# = 0 ]]; then
    killall -q polybar
    sleep 3

    # polybar top -c $HOME/.config/polybar/`hostname`.ini &
    polybar workspaces -c $HOME/.config/polybar/config.ini &
    polybar sys -c $HOME/.config/polybar/config.ini &
    polybar datetime -c $HOME/.config/polybar/config.ini &
else
    polybar $1 -c $HOME/.config/polybar/config.ini &
fi

