#!/usr/bin/env bash

# CACHE_FILE="$HOME/.cache/polybar-toggle-state"
CACHE_FILE="/tmp/polybar-toggle-state"
echo "1" >"$CACHE_FILE"

if [[ $# = 0 ]]; then
	killall -q polybar
	# sleep 3 # wait for polybar to shutdown, should be more than enough time

	if [[ $(hostname) = "prometheus" ]]; then
		runbg polybar workspaces -c $HOME/.config/polybar/config.ini
		runbg polybar sys -c $HOME/.config/polybar/config.ini
		runbg polybar clock -c $HOME/.config/polybar/config.ini
		pgrep "spotify" && launch-bar music
	else
		runbg polybar top -c $HOME/.config/polybar/config.ini &
	fi
else
	runbg polybar $1 -c $HOME/.config/polybar/config.ini &
fi
exit
