#!/usr/bin/env bash

MAIN_BROWSER=brave

case $1 in
    default)
        $MAIN_BROWSER
        ;;
    reset)
        if [[ $(xdotool getwindowfocus getwindowclassname) == "Brave-browser" ]]; then
            launch-browser default
            sleep 0.2
            xdotool key Super+Shift+U005C
            xdotool key Super+q
        else
            notify-send "window class: $(xdotool getwindowfocus getwindowclassname)"
        fi
        ;;
    set)
        profile=$2
        if [[ -z $2 ]]; then
            wd=$(date +"%w")
            h=$(date +"%k")
            if [[ $wd -gt 0 ]] && [[ $wd -lt 6 ]] && [[ $h -ge 9 ]] && [[ $h -le 20 ]]; then
                profile="work"
            else
                profile="default"
            fi
        fi
        # cp "$STOW_DIR/global/dot-config/firefox/$profile.ini" "$HOME/.mozilla/firefox/profiles.ini"
        cp "$CONFIG/firefox/$profile.ini" "$HOME/.mozilla/firefox/profiles.ini"
        ;;
esac


