#!/usr/bin/env bash
source parseargs

firefox=""
brave="ﱾ"
work=""
ta="拾"

options="$firefox\n$work\n$brave\n$ta"

sel=$(echo -e "$options" | rofi -no-fixed-num-lines -theme $HOME/.config/rofi/commmenu.rasi -dmenu)

case $sel in
$firefox)
	firefox
	;;
$work)
	firefox -P work
	;;
$brave)
	brave
	;;
$ta)
	firefox -P ta
	;;
esac
