#!/usr/bin/env bash

bat=`acpi | awk '{printf $4}' | tr -d "," | tr -d "%"`

i=1
while (( $bat > 15 )); do
    bat=`acpi | awk '{printf $4}' | tr -d "," | tr -d "%"`
    echo "check $i"
    i=$(($i+1))
    sleep 30
done
dunstify "low battery" -u "critical"

