#!/usr/bin/env bash
source parseargs

COLUMNS=100 exa --group-directories-first --icons -a
echo

if (( ${#args[@]} )); then
    printf "     \x1b[36m${args[@]}\x1b[0m\n"
    dir="du -ahd1 ${args[@]} 2>/dev/null | sed 's/${args[@]}\///g' | head -n-1 | sort -rh"
    total="du -sh ${args[@]} 2>/dev/null | awk '{\$2=\"Total:\"; print \$2 \" \" \$1}'"
else
    dir="du -ahd1 2>/dev/null | sed 's/\.\///' | sed '/\.$/d' | sort -rh"
    total="du -shc 2>/dev/null | head -n1 | awk '{\$2=\"Total:\"; print \$2 \" \" \$1}'"
fi

if [[ ${booleans[l]} = true ]]; then
    dir+=" | sed '/[[:digit:]]K/d'"
fi

eval $dir
echo
eval $total
