#!/usr/bin/env bash

if [[ ! `acpi 2>/dev/null` ]]; then
    [[ $1 == "get-len" ]] && echo 0
    exit 0
fi

empty=""
ten=""
twenty=""
thirty=""
fourty=""
fifty=""
sixty=""
seventy=""
eighty=""
ninety=""
full=""
charging=""

charge=`cat /sys/class/power_supply/BAT0/capacity`

if [[ `cat /sys/class/power_supply/BAT0/status` == "Charging" ]]; then
    icon=$charging
elif (( $charge <= 10 )); then
    icon=$empty
elif (( $charge <= 20 )); then
    icon=$ten
elif (( $charge <= 30 )); then
    icon=$twenty
elif (( $charge <= 40 )); then
    icon=$thirty
elif (( $charge <= 50 )); then
    icon=$fourty
elif (( $charge <= 60 )); then
    icon=$fifty
elif (( $charge <= 70 )); then
    icon=$sixty
elif (( $charge <= 80 )); then
    icon=$seventy
elif (( $charge <= 90 )); then
    icon=$eighty
elif (( $charge <= 95 )); then
    icon=$ninety
else
    icon=$full
fi

if (( $charge >= 50 )); then
    color=2
elif (( $charge >= 20 )); then
    color=3
elif (( $charge > 10 )); then
    color=11
else
    color=1
fi

if [[ $1 == "get-len" ]]; then
    str=" $charge% $icon "
    echo ${#str}
    exit 0
fi

echo "#[fg=color236]#[fg=color$color, bg=color236] $icon $charge% "
