#!/usr/bin/env bash

if [[ ! `acpi 2>/dev/null` ]]; then
    [[ $1 == "get-len" ]] && echo 0
    exit 0
fi

empty=""
ten=""
twenty=""
thirty=""
fourty=""
fifty=""
sixty=""
seventy=""
eighty=""
ninety=""
full=""
charging=""

bat=`acpi | head -n1 | awk '{printf $4}' | tr -d ","`
batnum=`echo $bat | tr -d "%"`

if [[ `acpi 2>/dev/null | awk '{printf $3}' | head -c8 | tr -d ','` == "Charging" ]]; then
    icon=$charging
elif (( $batnum <= 10 )); then
    icon=$empty
elif (( $batnum <= 20 )); then
    icon=$ten
elif (( $batnum <= 30 )); then
    icon=$twenty
elif (( $batnum <= 40 )); then
    icon=$thirty
elif (( $batnum <= 50 )); then
    icon=$fourty
elif (( $batnum <= 60 )); then
    icon=$fifty
elif (( $batnum <= 70 )); then
    icon=$sixty
elif (( $batnum <= 80 )); then
    icon=$seventy
elif (( $batnum <= 90 )); then
    icon=$eighty
elif (( $batnum <= 95 )); then
    icon=$ninety
else
    icon=$full
fi

if (( $batnum >= 75 )); then
    color=2
elif (( $batnum >= 50 )); then
    color=3
elif (( $batnum > 20 )); then
    color=11
else
    color=1
fi

if [[ $1 == "get-len" ]]; then
    str=" $bat $icon "
    echo ${#str}
    exit 0
fi

echo "#[fg=color236]#[fg=color$color, bg=color236] $bat $icon "
