#!/usr/bin/env bash

if [[ ! $(acpi 2>/dev/null) ]]; then
	[[ $1 == "get-len" ]] && echo 0
	exit 0
fi

empty=""
ten=""
twenty=""
thirty=""
fourty=""
fifty=""
sixty=""
seventy=""
eighty=""
ninety=""
full=""
charging=""

charge=$(cat /sys/class/power_supply/BAT0/capacity)

if [[ $(cat /sys/class/power_supply/BAT0/status) == "Charging" ]]; then
	icon=$charging
elif (($charge >= 95)); then
	icon=$full
elif (($charge >= 90)); then
	icon=$ninety
elif (($charge >= 80)); then
	icon=$eighty
elif (($charge >= 70)); then
	icon=$seventy
elif (($charge >= 60)); then
	icon=$sixty
elif (($charge >= 50)); then
	icon=$fifty
elif (($charge >= 40)); then
	icon=$fourty
elif (($charge >= 30)); then
	icon=$thirty
elif (($charge >= 20)); then
	icon=$twenty
elif (($charge >= 10)); then
	icon=$ten
else
	icon=$empty
fi

if (($charge > 20)); then
	color=2 # green
elif (($charge > 10)); then
	color=3 # yellow
# elif (($charge > 10)); then
# 	color=11 # orange
else
	color=1 # red
fi

if [[ $1 == "get-len" ]]; then
	str=" $charge% $icon "
	echo ${#str}
	exit 0
fi

echo "#[fg=color236]#[fg=color$color, bg=color236] $icon $charge% "
