#!/usr/bin/env bash

hidden_term() {
	tmux list-windows -F '#{window_name}' | grep -q ' '
}

get_hid_term() {
	tmux list-windows -F '#{window_name}::#{window_id}' | grep ' ' | awk -F '::' '{print $2}' | head -n1
}

get_panes_below() {
	if [[ $(tmux display-message -p '#{pane_at_top}') -ne 1 ]]; then tmux select-pane -U; fi
	tmux list-panes -F '#{pane_id} #{pane_top} #{pane_bottom}' | awk -v top=$(tmux display -p '#{pane_top}') -v bottom=$(tmux display -p '#{pane_bottom}') '$2 > bottom'
}

get_panes_beside() {
	tmux select-pane -L
	tmux list-panes -F '#{pane_id} #{pane_left} #{pane_right}' | awk -v left=$(tmux display -p '#{pane_left}') -v right=$(tmux display -p '#{pane_right}') '$2 > right'
}

d=${1:-h}

case $d in
h)
	if [[ $(get_panes_below | wc -l) -eq 0 ]]; then
		if hidden_term; then
			tmux join-pane -v -l 30% -s $(get_hid_term)
		else
			tmux split-window -c "#{pane_current_path}" -v -p 30
		fi
	else
		tmux select-pane -D
		tmux break-pane -d -n ' ' -t $(($(tmux list-windows -F '#{window_index}' | tail -n1) + 1))
	fi
	;;
v)
	if [[ $(get_panes_beside | wc -l) -eq 0 ]]; then
		if hidden_term; then
			tmux join-pane -h -l 30% -s $(get_hid_term)
		else
			tmux split-window -c "#{pane_current_path}" -h -p 30
		fi
	else
		tmux select-pane -R
		tmux break-pane -d -n ' ' -t $(($(tmux list-windows -F '#{window_index}' | tail -n1) + 1))
	fi
	;;
*)
	echo "invalid dir: h or v"
	;;
esac

# if hidden_term; then
# 	tmux select-pane -t 0
# 	tmux join-pane -v -l 30% -s ' '
# elif no_bot; then
# 	tmux select-pane -t 0
# 	tmux split-window -c "#{pane_current_path}" -v -p 30
# else
# 	tmux select-pane -t 1
# 	tmux break-pane -d -n ' ' -t $(($(tmux list-windows -F '#{window_index}' | tail -n1) + 1))
# 	[[ $HOSTNAME = "coeus" ]] && sleep 0.01 || sleep 0.3
# 	tmux next-window
# 	tmux previous-window
# fi
