#!/usr/bin/env bash
[[ ! -d ~/projects/neovim ]] && git clone git@github.com:neovim/neovim.git ~/projects/neovim
cd ~/projects/neovim
git fetch && git pull
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
