#!/bin/bash

function get_volume {
	amixer -D pulse get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
	amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | grep off >/dev/null
}

function send_notification {
	update_bar

	if is_mute; then
		dunstify "Muted" --icon ~/.config/dunst/images/mute.png -r 1234
	else
		volume=$(get_volume)
		bar=$(seq --separator="─" 0 "$((volume / 3))" | sed 's/[0-9]//g')
		# Send the notification
		dunstify "Volume" -h int:value:"$volume" --icon ~/.config/dunst/images/volume.png -r 1234
	fi
}

function update_bar {
    pid=$(pgrep -f "polybar sys" || pgrep -f "polybar top")
    polybar-msg -p $pid hook volume 1 &>/dev/null

}

[[ $# = 0 ]] && get_volume && exit 0

case $1 in
up)
	pactl set-sink-mute @DEFAULT_SINK@ 0
	volume=$(get_volume)
	if [ $volume -lt 100 ]; then
		pactl set-sink-volume @DEFAULT_SINK@ +5%
	fi
	send_notification
	;;
down)
	pactl set-sink-mute @DEFAULT_SINK@ 0
	volume=$(get_volume)
	if [ $volume -gt 0 ]; then
		pactl set-sink-volume @DEFAULT_SINK@ -5%
	fi
	send_notification
	;;
mute)
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	send_notification
	;;
set)
	pactl set-sink-volume @DEFAULT_SINK@ $2%
	update_bar
	;;
esac
