#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$(dirname "$0")"/utils

volicons=("󰕿" "󰖀" "󰕾" "")
date="$XDG_CACHE_HOME/eww/osd_vol.date"

gen_output() {
	percent="$(volume)"
	lvl=$(awk -v n="$percent" 'BEGIN{print int(n/25)}')

	if volume ismuted; then
		icon="󰸈"
	else
		icon="${volicons[$lvl]}"
	fi

	pamixer --list-sources | rg -q Running
	[ $? -eq 1 ] && in_use=0 || in_use=1

	echo '{"icon": "'"$icon "'", "percent": "'"$percent"'", "in_use": "'"$in_use"'"}'
}

case "$1" in
"osd")
	osd "$date"
	;;

"")
	# initial values
	in_use=0
	last_time=$(get_time_ms)
	gen_output
	osd_handler "osd-volume" &

	# event loop
	pactl subscribe | rg --line-buffered ".*(source|sink).*" | while read -r event; do
		current_time=$(get_time_ms)
		delta=$((current_time - last_time))
		# 50ms debounce
		if [[ $delta -gt 50 ]]; then
			gen_output
			# reset debounce timer
			last_time=$(get_time_ms)
		fi
	done
	;;

*) echo "wrong usage" ;;
esac
