#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	notify-send "Launching eww daemon"
	${EWW} daemon
fi

## Open widgets
run_eww() {
	${EWW} --config "$CFG" open-many \
		background \
		profile \
		system \
		clock \
		cal \
		music \
		github \
		hackernews \
		twitter \
		youtube \
		weather \
		apps \
		mail \
		logout \
		sleep \
		reboot \
		poweroff \
		folders
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
		background profile system clock cal music github \
		hackernews twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm "$FILE"
fi
