#!/bin/bash

DEVFILE=$HOME/.config/bt/devices

# Power on bluetooth controller
[[ `bluetoothctl show | rg "Powered" | awk '{print $2}'` == "yes" ]] || bluetoothctl power on

# Load associative array with device name -> mac address
IFS="\n"

readarray -t a < "$DEVFILE"

declare -A devices

for e in ${a[@]}; do
    k=`echo $e | awk '{print $1}'`
    v=`echo $e | awk '{print $2}'`
    devices+=( [$k]=$v )
done

has_dev() {
    [[ ${devices[$1]+true} ]]
}

get_dev() {
    if [[ -n $1 ]]; then
        dev=$1
    else
        dev=`printf "%s\n" ${!devices[@]} | fzf --header="device menu" --info="hidden"`
    fi
    has_dev $dev || exit 0
    echo $dev
}


case $1 in
    connect | con | c)
            dev=`get_dev $2`
            [[ -z $dev ]] && echo "Invalid device" && exit 1
            mac=${devices[$dev]}
            bluetoothctl connect $mac || exit 1
            [[ $dev = "wacom" ]] && config-wacom
        ;;
    disconnect | discon | d)
            dev=`get_dev $2`
            [[ -z $dev ]] && echo "Invalid device" && exit 1
            mac=${devices[$dev]}
            bluetoothctl disconnect $mac || exit 1
        ;;
    toggle | t)
        dev=`get_dev $2`
        [[ -z $dev ]] && echo "Invalid device" && exit 1
        mac=${devices[$dev]}
        connected=`bluetoothctl info | grep "$dev" -A 8 | grep "Connected" | awk '{ print $2 }'`
        if [[ $connected == 'yes' ]]; then
            bluetoothctl disconnect $mac || exit 1
        else
            bluetoothctl connect $mac || exit 1
        fi
        ;;
    add | a)
        [[ -z $2 || -z $3 ]] && echo "Usage: bt add [name] [mac]" && exit 1
        echo "$2 $3" >> "$DEVFILE" && echo "Sucessfully added $2 ($3) to the list of devices"
        ;;
    remove | r)
        [[ -z $2 ]] && echo "Usage: bt remove [name]" && exit 1
        ! has_dev $2 && echo "Invalid device \"$2\"" && exit 1
        sed -i "/^$2 /d" "$DEVFILE"
        ;;
    menu | m)
        echo TODO: launch rofi
        ;;
    *)
        echo "Usage: bt [connect | disconnect | add [name] [mac] | remove [name]]"
        ;;
esac
