#!/bin/bash

# see man zscroll for documentation of the following parameters
zscroll -l 100 \
    --delay 0.5 \
    --scroll-padding "          " \
    --match-command "playerctl --player=spotify status 2>/dev/null" \
    --match-text "Playing" "--scroll 1" \
    --match-text "Paused" "--scroll 0" \
    --update-check true ~/scripts/get-song 2>/dev/null &
wait

