#!/usr/bin/env bash

next=`cat /tmp/toggle-date-time`
polybar-msg -p "$(pgrep -f "polybar datetime")" hook date-time $next &>/dev/null

if [[ $next = 1 ]]; then
    echo "2" > /tmp/toggle-date-time
else
    echo "1" > /tmp/toggle-date-time
fi

