format = """
$nix_shell\
$hg_branch\
$docker_context\
$container\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$conda\
$memory_usage\
$aws\
$openstack\
$env_var\
$crystal\
$lua\
$jobs\

    $fill\
    $cmd_duration\
    $line_break\

$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\

    $fill\
    $time\
    $line_break\

$username\
$hostname\
${custom.lvl}\
$shell\
$status\
$character\
"""

command_timeout = 500

[character]
success_symbol = "[](bold green)"
vicmd_symbol = "[](bold #fab387)"
error_symbol = "[󱎘](bold red)"

[fill]
symbol = " "

[cmd_duration]
min_time = 1_000
style = "#72778C"
format = "[󱦟 $duration]($style) "

[time]
time_format = "%H:%M"
format = "[$time]($style) "
style = "#72778C"
disabled = false

[package]
disabled = true

[jobs]
symbol = "󱦟"
style = "#72778C"
format = "[$symbol (×$number)]($style) "

[git_branch]
symbol = "󰘬 "
format = '[$symbol$branch]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "#898FA6"
stashed = "󰆓 "
conflicted = "󰗖 "
ahead = "󰐙 ×${count} "
behind = "󰍷 ×${count} "
diverged = "󰐙 ×${ahead_count} 󰍷 ×${behind_count} "
modified = "󱇧 ×${count} "
untracked = "󱀶 ×${count} "
staged = "󰝒 ×${count} "
renamed = "󰪹 ×${count} "
deleted = "󱀭 ×${count} "

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style)'
symbol = ' '
disabled = true


[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)@"
disabled = true

[hostname]
ssh_only = true
format = "[$hostname](bold red) "
disabled = false

[directory]
truncation_length = 8
read_only = " "

[directory.substitutions]
"~/projects" = "projects"

[custom.lvl]
command = "show_sh_lvl"
when = "show_sh_lvl"
style = "#FFA570"
format = "[($output )]($style)"
disabled = true

[shell]
disabled = false
zsh_indicator = ""
bash_indicator = "𝐁 "
xonsh_indicator = "𝐗 "
unknown_indicator = " "
format = "$indicator"

[nix_shell]
format = '[$symbol $name]($style) '
symbol = "󱄅"

[python]
symbol = "󰌠 "
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = "󰎙 "
format = "[$symbol$version]($style) "
style = "bold blue"

[lua]
symbol = "󰢱 "
format = "[$symbol$version]($style) "

[cmake]
symbol = "󰔷 "
format = "[$symbol$version]($style) "

[ruby]
symbol = "󰴭 "
format = "[$symbol$version]($style) "

[java]
symbol = "󰬷 "
format = "[$symbol$version]($style) "

[perl]
symbol = "/ "
format = "[$symbol$version]($style) "

[rust]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = "󱘗 "
style = "bold red"

[golang]
format = "[$symbol($version)]($style) "
symbol = " "
style = "bold blue"
