#!/usr/bin/env bash

if ! command -v acpi &>/dev/null; then
    echo
    exit
fi

icons=("󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹")
num_icons=$(awk -v n="${#icons[@]}" 'BEGIN{print 100 / n}')

geticon() {
	level=$(awk -v n="$percent" -v c="$num_icons" 'BEGIN{print int(n/c-1)}')
	echo "${icons[$level]}"
}

gettime() {
	if [ "$state" = "Discharging" ]; then
		echo "$info" | jq -r '.charge_remaining'
	else
		echo "$info" | jq -r '.until_charged'
	fi

}

color() {
    if [[ $state == "Discharging" ]]; then
        [[ $percent -le 15 ]] && echo "#f38ba8" || echo "#a6e3a1"
    else
        echo "#f9e2af"
    fi
}

status() {
	out=""
	if [ "$state" = "fully-charged" ]; then
		out+="Fully Charged"
	else
		[[ "$state" == "Charging" ]] && out+="Charging, "
		out+="$(gettime) left"
	fi
	echo "$out"
}

gen_output() {
	info="$(acpi | jc --acpi | jq '.[]')"
	percent="$(echo "$info" | jq -r '.charge_percent')"
    [[ -n $percent ]] || percent='100'
	state="$(echo "$info" | jq -r '.state')"

	echo '{"icon": "'"$(geticon)"'", "percent": '"$percent"', "status": "'"$(status)"'", "color": "'"$(color)"'"}'
}

while true; do
	gen_output
	sleep 3
done
