#!/usr/bin/env bash

get_status() {
	echo "$1" | rg -q "Playing" && echo "󰏤" || echo "󰐊"
}

get_cover() {
	mkdir -p "/tmp/eww_covers"
	cd "/tmp/eww_covers" || exit

	COVER_URL="$1"

	if [[ "$COVER_URL" = https* ]]; then
		FILENAME=$(basename "$COVER_URL")
		if [ ! -e "$FILENAME" ]; then
			wget -N "$COVER_URL" -o /dev/null
		fi

		IMG="/tmp/eww_covers/$FILENAME"
	elif [ -n "$COVER_URL" ]; then
		IMG="$COVER_URL"
	else
		IMG=""
	fi

	echo "$IMG"
}
sanitize() {
	echo "${1//\"/\\\"}"
}

prev_cover=''
prev_artist=''
prev_title=''

player_arg=""
if pgrep "spotify" >/dev/null; then
    player_arg="-p spotify"
fi

echo $player_arg

playerctl $player_arg -F metadata -f '{{title}}\{{artist}}\{{status}}\{{mpris:artUrl}}' 2>/dev/null | while IFS="$(printf '\')" read -r title artist status cover; do
    player_arg=""
    if pgrep "spotify" >/dev/null; then
        player_arg="-p spotify"
    fi
	if [[ -z "$title" ]]; then
		IFS="$(printf '\')" read -r title artist status cover <<<$(playerctl $player_arg metadata -f '{{title}}\{{artist}}\{{status}}\{{mpris:artUrl}}')
	fi

	if [ "$cover" != "$prev_cover" ]; then
		COVER=$(get_cover "$cover")

		if [ "$COVER" != "" ]; then
			cols=$(convert "$COVER" -colors 1 -format "%c" histogram:info: | awk '{print $3}')
			border=$(echo "$cols" | head -1)

			if [ ! -e "$COVER"_bg ]; then
				brightness=$(convert "$COVER" -colorspace HSI -channel b -separate +channel -scale 1x1 -format "%[fx:100*u]\n" info:)
				if [ "${brightness%.*}" -lt 25 ]; then
					darken=false
				else
					darken=true
				fi

				convert -scale 10% -blur 0x2.5 -resize 1000% $([ "$darken" = "true" ] && echo "-brightness-contrast -30x10") "$COVER" "$COVER"_bg
			fi
			bg="url('"
			bg+="$COVER"_bg
			bg+="')"
		else
			border="#28283d"
		fi
	fi

	if [ "$prev_artist" != "$artist" ]; then
		prev_artist="$artist"
		thisArtist="$(sanitize "$artist")"
	fi

	if [ "$prev_title" != "$title" ]; then
		prev_title="$title"
		thisTitle="$(sanitize "$title")"
	fi

	thisStatus="$(get_status "$status")"
	prevIcon="󰒮"
	nextIcon="󰒭"

	if [[ ! -z "$thisTitle" ]]; then
		full="$thisTitle – $thisArtist"

	else
		full=""
		thisStatus=""
		prevIcon=""
		nextIcon=""
	fi
	echo '{"artist": "'"$thisArtist"'", "title": "'"$thisTitle"'", "full": "'"$full"'", "status": "'"$thisStatus"'", "cover": "'"$COVER"'", "border": "'"$border"'", "bg": "'"$bg"'", "prevIcon": "'"$prevIcon"'", "nextIcon": "'"$nextIcon"'"}'

	prev_cover=$cover
done
