#!/bin/bash

rofi_command="rofi -no-fixed-num-lines -theme $HOME/.config/polybar/themes/powermenu.rasi"

if [[ $(hostname) = "coeus" ]]; then
	rofi_command+=" -m DP-0"
fi

# Options
shutdown="󰐥"
reboot="󰜉"
suspend="󰒲"
logout="󰿅"

# Variable passed to rofi
options="$shutdown\n$reboot\n$suspend\n$logout"

chosen="$(echo -e "$options" | $rofi_command -dmenu)"

ask_sync() {
	sync=""
	nosync=" ﰸ"
	options="$sync\n$nosync"
	chosen="$(echo -e "$options" | $rofi_command -dmenu)"
	if [[ $chosen == $sync ]]; then
		cloud upload all
	fi
	[[ -n $chosen ]]
}

case $chosen in
$shutdown)
	ask_sync && dunstify "Shutting down..." && sleep 1 && sudo poweroff
	;;
$reboot)
	ask_sync && dunstify "Rebooting..." && sleep 1 && sudo reboot
	;;
$suspend)
	#betterlockscreen -l &
	sleep 0.5
	systemctl suspend
	;;
$logout)
	session=$(loginctl session-status | head -n 1 | awk '{print $1}')
	ask_sync && dunstify "Returning to tty..." && sleep 1 && loginctl terminate-session $session
	;;
esac
