#!/bin/bash

rofi_command="rofi -no-fixed-num-lines -theme $HOME/.config/polybar/themes/powermenu.rasi"

if [[ `hostname` = "coeus" ]]; then
    rofi_command+=" -m DP-0"
fi

# Options
shutdown="󰐥"
reboot="󰜉"
suspend="󰒲"
logout="󰿅"

# Variable passed to rofi
options="$shutdown\n$reboot\n$suspend\n$logout"

chosen="$(echo -e "$options" | $rofi_command -dmenu)"

case $chosen in
    $shutdown)
        notify-send "Syncing..."
        [[ $HOSTNAME = "coeus" ]] && cloud upload all
        notify-send "Shutting down"
        sleep 1
	    sudo poweroff
        ;;
    $reboot)
        notify-send "Syncing..."
        [[ $HOSTNAME = "coeus" ]] && cloud upload all
        notify-send "Rebooting"
        sleep 1
	    sudo reboot
        ;;
    $suspend)
	    #betterlockscreen -l &
	    sleep 0.5
        systemctl suspend
        ;;
    $logout)
        [[ $HOSTNAME = "coeus" ]] && cloud upload all
        session=`loginctl session-status | head -n 1 | awk '{print $1}'`
        loginctl terminate-session $session
        ;;
esac
