#!/usr/bin/env bash

postal=$(cat ~/.cache/postalcode)
prefix=""
fmt=""

case $1 in
temp)
	fmt="%t"
	;;
feel)
	fmt="%f"
	prefix="~"
	;;
toggle)
	CACHE_FILE=~/.cache/polybar/weather
	if [[ ! -e $CACHE_FILE ]]; then
		mkdir -p $(dirname $CACHE_FILE)
		echo "1" >$CACHE_FILE
	fi
	cur=$(cat ~/.cache/polybar/weather)
	nxt=$((3 - cur)) # 2 if cur is 1 // 1 if cur is 2
	echo $nxt >$CACHE_FILE
	polybar-msg -p "$(pgrep -f "polybar clock")" hook weather $nxt &>/dev/null
	exit
	;;
esac

icon=$(curl "wttr.in/?format=%c")
[[ -z $postal ]] && notify-send "Weather" "Postal code not set. Using IP" --icon=~/.config/dunst/images/brightness.png
temp="$(curl -q "wttr.in/$postal?format=$fmt")"

temp=${temp//+/}
echo "$icon $prefix$temp"
