#!/usr/bin/env bash

CACHE_FILE=~/.cache/polybar/weather
prefix="  "
temp="n/a"

case $1 in
temp)
	temp=$(weather --temp)
	;;
feel)
	prefix="~"
	temp=$(weather --feels)
	;;
toggle)
	cur=$(cat $CACHE_FILE)
	nxt=$((3 - cur)) # 2 if cur is 1 // 1 if cur is 2
	echo $nxt >$CACHE_FILE
	polybar-msg -p "$(pgrep -f "polybar clock")" hook weather $nxt &>/dev/null
	exit
	;;
start)
	mkdir -p $(dirname $CACHE_FILE)
	echo "1" >$CACHE_FILE

	# while internet is down wait in 1m intervals
	echo "tmp"
	if ! ping -q -c1 8.8.8.8; then
		runbg ~/.config/polybar/scripts/weather-wait
		echo "󱓤     "
	else
		polybar-msg -p "$(pgrep -f "polybar clock")" hook weather 1 &>/dev/null
	fi
	exit
	;;
esac

icon=$(weather --icon)
echo "$icon   $prefix$temp"
