#!/usr/bin/env bash

icon=$(curl "wttr.in/?format=%c")
postal=$(cat ~/.cache/postalcode)

case $1 in
temp)
	[[ -z $postal ]] && notify-send "Weather" "Postal code not set. Using IP" --icon=~/.config/dunst/images/brightness.png
	temp=$(curl -q "wttr.in/$postal?format=%t")
	;;
feel)
	[[ -z $postal ]] && notify-send "Weather" "Postal code not set. Using IP" --icon=~/.config/dunst/images/brightness.png
	temp="~$(curl -q "wttr.in/$postal?format=%f")"
	;;
toggle)
	CACHE_FILE=~/.cache/polybar/weather
	if [[ ! -e $CACHE_FILE ]]; then
		mkdir -p $(dirname $CACHE_FILE)
		echo "1" >$CACHE_FILE
	fi
	cur=$(cat ~/.cache/polybar/weather)
	nxt=$((3 - cur)) # 2 if cur is 1 // 1 if cur is 2
	echo $nxt >$CACHE_FILE
	polybar-msg -p "$(pgrep -f "polybar clock")" hook weather $nxt &>/dev/null
	;;
*)
	temp=$(curl "wttr.in/?format=%t")
	;;
esac

temp=${temp//+/}
echo "$icon $temp"
