#!/bin/bash
bluetoothctl power on


dev=""
case $1 in
    ap)
        dev="E4:90:FD:90:2B:52"
        ;;
    wacom)
        dev="E0:9F:2A:16:65:E4"
        ;;
esac

if [ -z $2 ]
then
    connected=`bluetoothctl info | grep "$dev" -A 8 | grep "Connected" | awk '{ print $2 }'`
	if [[ $connected == 'yes' ]]
	then
		bluetoothctl disconnect $dev
	else
		bluetoothctl connect $dev
	fi
else
	case $2 in
		c)
			bluetoothctl connect $dev
			;;
		d)
			bluetoothctl disconnect $dev
			;;
	esac
fi

if [ $1 = "wacom" ]
then
    # set screen
    screens="main left right"
    screen=`printf "%s\n" $screens | fzf`
    case $screen in
        "main")
            screen=0
            ;;
        "left")
            screen=1
            ;;
        "right")
            screen=2
            ;;
    esac
    xsetwacom set "Wacom Intuos BT S Pen stylus" MapToOutput "HEAD-$screen"

    # config stylus
    xsetwacom set "Wacom Intuos BT S Pen stylus" PressureCurve 0 100 40 80
    xsetwacom set "Wacom Intuos BT S Pen stylus" Button 2 21
    xsetwacom set "Wacom Intuos BT S Pen stylus" Button 3 22

    # config pad
    xsetwacom set "Wacom Intuos BT S Pad pad" Button 1 "key del"
    xsetwacom set "Wacom Intuos BT S Pad pad" Button 2 "key +ctrl z -ctrl"
    xsetwacom set "Wacom Intuos BT S Pad pad" Button 3 "key +ctrl c -ctrl"
    xsetwacom set "Wacom Intuos BT S Pad pad" Button 8 "key +ctrl v -ctrl"
fi
