#!/usr/bin/env bash


langs=( "lua" "python" "c" "bash" "typescript" )
cmds=( "xargs" "find" "mv" "sed" "awk" "tmux" )
all=(${langs[@]} ${cmds[@]})

sel=`printf "%s\n" ${all[@]} | fzf`

if [[ -z $sel ]]; then
    exit 0
fi

read -p "Enter Query: " query

if `echo ${langs[@]} | grep -w -q $sel`; then
    query=`echo $query | tr ' ' '+'`
    tmux neww bash -c "echo \"curl cht.sh/$sel/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done"
else
    echo cmd
    tmux neww bash -c "curl -s cht.sh/$sel~$query | less"
fi
