#!/usr/bin/env bash

session=`tmux display-message -p '#S'`

# ~/.dotfiles/coeus/.config/kitty/kitty.conf
case $session in
    main)
        echo 5
        ;;
    nn)
        echo 5
        ;;
    os)
        echo 3
        ;;
    paradigms)
        echo 2
        ;;
    psyc)
        echo 1
        ;;
    comm)
        echo 4
        ;;
    ta)
        echo 11
        ;;

    *)
        echo 7
        ;;
esac

