#!/usr/bin/env bash

# To use, add this script to your path, and make sure it is executable

# To auto-launch with your terminal, add -c "tm startup || exec [shell]" to
# your shell in your terminal config. See coeus/.config/kitty/kitty.conf for
# an example.

# To enable the floating window in tmux, add this line to your tmux.conf:
# bind-key Enter display-popup -E "tm"
# this binds the popup to <prefix>Enter

# NOTE: if you do not also grab my triangles script this script won't work.
# change startcmd to a blank string (or whatever you want) to fix
# also change the shell to whatever shell you use

shell="zsh"
startcmd="triangles && echo"
if [[ -n $startcmd ]]; then
    startcmd="$startcmd && exec $shell"
else
    startcmd="exec $shell"
fi

sessions=`tmux ls 2>/dev/null | awk '{print $1}' | sed 's/://'`

not_in_tmux() {
    [[ -z $TMUX ]]
}

session_exists() {
    tmux has-session -t $1 &> /dev/null && true
}

attach_session() {
    if not_in_tmux; then
        if ! session_exists $1; then
            tmux new -s $1 -n main "$startcmd"
        else
            tmux attach -t $1
        fi
    else
        if ! session_exists $1; then
            tmux new -s $1 -d -n main "$startcmd"
        fi
        tmux switch -t $1
    fi
}

if [[ $# == 0 ]]; then
    if [[ -z $sessions ]]; then
        sel="NEW"
    else
        sessions="$sessions NEW END KILL"
        sel=`printf "%s\n" $sessions | fzf --header="tmux menu" --info="hidden"`
        [[ -z $sel ]] && exit 1
    fi

    case $sel in
        NEW)
            tm new
            ;;
        END)
            tm end
            ;;
        KILL)
            tm kill
            ;;
        *)
            tm attach $sel
            ;;
    esac
else
    case $1 in
        new | n)
            if [[ -z $2 ]]; then
                name=`read -p "session name: " -e tmp; echo $tmp`
            else
                name=$2
            fi
            [[ -z $name ]] && echo "no session name" && exit 1

            cd ~
            attach_session $name
            ;;
        attach | a)
            if [[ -z $2 ]]; then
                sessions="$sessions NEW"
                name=`printf "%s\n" $sessions | fzf --header="attach menu" --info="hidden"`
            else
                name=$2
            fi
            [[ -z $name ]] && echo "no session name" && exit 1

            if [[ $name == "NEW" ]]; then
                tm new
            else
                attach_session $name
            fi
            ;;
        kill | k | x)
            if [[ -n $sessions ]]; then
                if [[ -n $2 ]]; then
                    sel=$2
                else
                    sessions="$sessions ALL"
                    sel=`printf "%s\n" $sessions | fzf --header="kill menu" --info="hidden"`
                    [[ -z $sel ]] && exit 0
                fi

                if [[ $sel == "ALL" ]]; then
                    tmux kill-server
                else
                    tmux kill-session -t $sel
                fi
            else
                echo "no tmux sessions"
                exit 1
            fi
            ;;
        end | e | q)
            not_in_tmux && echo "not in a tmux session, nothing to end" && exit 1
            old=`tmux display-message -p '#S'`
            tm attach && [[ `tmux display-message -p '#S'` != $old ]] && tm kill $old
            ;;
        startup | s)
            wtitle=`wmctrl -l | rg $(xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}' | sed 's/0x//') | awk '{print $4}'`
            if [[ $wtitle == "scratch" ]]; then
                attach_session "scratch"
            else
                if session_exists "main"; then
                    tm
                else
                    tmux new -s main -n main "$startcmd"
                fi
            fi
            ;;
        *)
            echo "Usage: tm [new [session-name] | attach [session-name] | kill [session-name] | startup | end]"
            echo
            echo "Main menu: tm"
    esac
fi

