#!/usr/bin/env bash

sessions=`tmux ls 2>/dev/null | awk '{print $1}' | sed 's/://'`

not_in_tmux() {
    [[ -z $TMUX ]]
}

session_exists() {
    tmux has-session -t $1 &> /dev/null && true
}

attach_session() {
    if not_in_tmux; then
        if ! session_exists $1; then
            tmux new -s $1 -n main "triangles && echo && exec zsh"
        else
            tmux attach -t $1
        fi
    else
        if ! session_exists $1; then
            tmux new -s $1 -d -n main "triangles && echo && exec zsh"
        fi
        tmux switch -t $1
    fi
}

if [[ $# == 0 ]]; then
    if [[ -z $sessions ]]; then
        sel="NEW"
    else
        sessions="$sessions NEW KILL"
        sel=`printf "%s\n" $sessions | fzf --header="session menu" --info="hidden"`
        [[ -z $sel ]] && exit 1
    fi

    if [[ $sel == "NEW" ]]; then
        tm new
    elif [[ $sel == "KILL" ]]; then
        tm kill
    else
        tm attach $sel
    fi
else
    case $1 in
        new)
            if [[ -z $2 ]]; then
                name=`read -p "session name: " -e tmp; echo $tmp`
            else
                name=$2
            fi
            [[ -z $name ]] && echo "no session name" && exit 1
            cd ~
            attach_session $name
            ;;
        attach)
            name=$2
            [[ -z $name ]] && echo "no session name" && exit 1
            attach_session $name
            ;;
        kill)
            if [[ -n $sessions ]]; then
                if [[ -n $2 ]]; then
                    sel=$2
                else
                    sessions="$sessions ALL"
                    sel=`printf "%s\n" $sessions | fzf --header="kill session" --info="hidden"`
                    [[ -z $sel ]] && exit 0
                fi

                if [[ $sel == "ALL" ]]; then
                    tmux kill-server
                else
                    tmux kill-session -t $sel
                fi
            else
                echo "no tmux sessions"
                exit 1
            fi
            ;;
        startup)
            wtitle=`wmctrl -l | rg $(xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}' | sed 's/0x//') | awk '{print $4}'`
            if [[ $wtitle == "scratch" ]]; then
                attach_session "scratch"
            else
                if session_exists "main"; then
                    tm
                else
                    tmux new -s main -n main "triangles && echo && exec zsh"
                fi
            fi
            ;;
    esac
fi

