#!/usr/bin/env bash

song=`get-song`
len=${#song}
w=`tmux list-windows -F \#{window_width} | head -n1`

# subtract len of session_name + len of window names
count=$((($w-30-$len-($len/2 + 1))/2))
spaces=`printf '%*s' $count`


echo "$song$spaces"

