#!/usr/bin/env bash

song=`get-song`
len=${#song}
widx=`tmux display-message -p '#{window_index}'`
w=`tmux list-windows -F "#{window_index} #{window_width}" | grep -E "^$widx" | awk '{print $2}'`

sname=`tmux display-message -p '#S'`
sname=${#sname}

wnames=`tmux lsw -F \#W`
wcount=`echo $wnames | wc -w`
wnames=${#wnames}
left_space=$((($sname+4)+wnames+(2*$wcount)))

right_space=25
if [[ `hostname` == "prometheus" ]]; then
    right_space=$right_space+7
else
    song="  $song"
    len=${#song}
fi


remaining=$(($w - ($left_space+$right_space+$len)))
if (( $remaining > 1 )); then
    count=$(($remaining/2))
    spaces=`printf '%*s' $count`
    echo "$song$spaces"
fi
