#!/usr/bin/env bash

files=(
    nvim $DOTFILES/.config/nvim
    zsh $DOTFILES/.config/zsh
    scripts $DOTFILES/scripts

    starship $DOTFILES/.config/starship.toml
    kitty $DOTFILES/.config/kitty/kitty.conf
    xmonad $DOTFILES/.config/xmonad/xmonad.hs
    tmux $DOTFILES/.config/tmux/tmux.conf
    x11 $DOTFILES/.config/X11/xinitrc

    alacritty $DOTFILES/.config/alacritty/alacritty.yml
    xonsh $DOTFILES/.config/xonsh
    fish $DOTFILES/.config/fish
)

file=`printf "%s %s\n" ${files[@]} | fzf --with-nth 1 | awk '{print $2}'`

if [[ ! -z $file ]]; then
    nvim $file
fi

